on:
  push:
    tags: 
      - v[0-9].*.*
jobs: 
    cicd:
        uses: durgeshnttdata/workflow-template/.github/workflows/workflowTag.yml@main
        with:
            appName: mulesoft-sfdc-acumatica-sync
            
        secrets: inherit 
