on:
  push:
    branches: [ main ]

jobs: 
    cicd:
        uses: durgeshnttdata/workflow-template/.github/workflows/workflowDev.yml@main
        with:
            appName: mulesoft-sfdc-acumatica-sync
            
        secrets: inherit 
